### ISSUE TITLE
 Error 1064

### ISSUE THREAD

**Issue by hlz217057** [hyahm/ITflow#10]
![image](https://user-images.githubusercontent.com/32893570/95700639-20c11400-0c7a-11eb-89ce-58b2c004e479.png)

**Comment by hyahm** [comment]
请截取下go的日志，

**Comment by hlz217057** [comment]
> 请截取下go的日志，

 C:/Users/Administrator/ITflow/go/internal/project/add.go:46 - Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1

**Comment by hyahm** [comment]
代码pull一下， 再次运行

**Comment by hyahm** [comment]
还有个bug， 稍等

**Comment by hyahm** [comment]
可以了

**Comment by hlz217057** [comment]
> 可以了

ok 我试试
