### ISSUE TITLE
bug发布失败

### ISSUE THREAD

**Issue by hlz217057** [hyahm/ITflow#12]
C:/Users                                               /Administrator/ITflow2/go/internal/project/myprojec                                               t.go:52 - sql: no rows in result set
--

**Comment by hyahm** [comment]
![image](https://user-images.githubusercontent.com/22030094/95711765-0eed6a00-0c96-11eb-8bb4-7a446a385e09.png)

先确定这里是都都填满了

**Comment by hyahm** [comment]
![image](https://user-images.githubusercontent.com/22030094/95711960-668bd580-0c96-11eb-8336-947d95f0f1c3.png)

这里也是有值的

**Comment by hlz217057** [comment]
> ![image](https://user-images.githubusercontent.com/22030094/95711960-668bd580-0c96-11eb-8336-947d95f0f1c3.png)
> 
> 这里也是有值的

默认值填了，其他都是填好的，提示成功，但是并没有入库，刷新后，在所有bug都看不到

**Comment by hyahm** [comment]
![image](https://user-images.githubusercontent.com/22030094/95712250-0cd7db00-0c97-11eb-9923-2836aa58d178.png)

这里默认是没选的， 需要勾选一下

**Comment by hlz217057** [comment]
感觉可以改进下，加个 “all” 作为默认所有的

**Comment by hyahm** [comment]
加了太麻烦， 正常用的话一般也就选1，2,个就够了

**Comment by hlz217057** [comment]
> 加了太麻烦， 正常用的话一般也就选1，2,个就够了

还有一个问题就是：项目管理添加项目，如果用户组中没有添加管理员admin，发布bug就看不到，这点有点尴尬！！

**Comment by hyahm** [comment]
创建者不需要权限也能看到自己创建的

**Comment by hlz217057** [comment]
> 创建者不需要权限也能看到自己创建的

我是说发布bug时，看不到项目

**Comment by hyahm** [comment]
编辑对应项目的用户组， 里面添加进去就可以看到了

**Comment by hlz217057** [comment]
> 编辑对应项目的用户组， 里面添加进去就可以看到了

这个知道，就是对于admin看不到，挺难受的，他作为超级管理员，按道理都是可以的；

还有一个问题是：其他管理创建用户组，admin竟然无法操作，admin删除后，刷新还在，这个是不是bug？？？

**Comment by hyahm** [comment]
可以试试， 超级管理员应该是什么都能看到的
如果看不到就是有bug了

**Comment by hyahm** [comment]
貌似管理员是没有权限修改删除其他人的东西的， 只能看， 除非给管理员分配的权限

**Comment by hlz217057** [comment]
> 貌似管理员是没有权限修改删除其他人的东西的， 只能看， 除非给管理员分配的权限

你可以等级admin，创建一个用户组，不添加admin，然后添加一个项目，你在发布bug，解决项目就看不到，没法选

**Comment by hlz217057** [comment]
登录admin

**Comment by hlz217057** [comment]
> 貌似管理员是没有权限修改删除其他人的东西的， 只能看， 除非给管理员分配的权限

admin啊，不可能不能操作吧，提示删除，但是刷新还在

**Comment by hyahm** [comment]
我增加一些提示先， 关于admin可以操作的问题后面再说

**Comment by hyahm** [comment]
拉最新的代码， 我看了下 此项目都没有删除bug的功能
