### ISSUE TITLE
添加的用户不能在系统创建任务吗？

### ISSUE THREAD

**Issue by gerrywp** [hyahm/ITflow#16]
添加的用户登录进系统之后，左侧菜单栏一片空白，没有功能可以用啊，请问需要如何配置？
![image](https://user-images.githubusercontent.com/16008976/147621998-44816793-0e0f-450f-959a-54e1712a6d1f.png)

**Comment by hyahm** [comment]
控制台看看

**Comment by gerrywp** [comment]
> 控制台看看

![image](https://user-images.githubusercontent.com/16008976/147630528-eed176b3-9d38-4c60-aed7-cfab2c0ca408.png)
GO的控制台没有什么可用信息啊

**Comment by hyahm** [comment]
用户权限看下

**Comment by hyahm** [comment]
知道了
