### ISSUE TITLE
任务转交这里显示的不是昵称而是姓名

### ISSUE THREAD

**Issue by gerrywp** [hyahm/ITflow#17]
显示不友好
![image](https://user-images.githubusercontent.com/16008976/147647397-1d39d6a4-31a8-4ba1-9084-0dd6f2f34619.png)

**Comment by hyahm** [comment]
昵称用来登录的，   姓名方面找人

**Comment by gerrywp** [comment]
> 昵称用来登录的， 姓名方面找人

这里应该显示姓名吧，这里显示的都是昵称，分配任务的时候又是显示姓名

**Comment by gerrywp** [comment]
创建任务那里显示的是 姓名，这里显示的不友好噢。目前程序还不完善吧，领取任务状态也没变，目前我暂时用不起来。
还是谢谢你的解答，加油。我自己也没时间写代码，不然我就自己改了!

**Comment by hyahm** [comment]
好的， 看到了， 里面显示基本都是姓名
