### ISSUE TITLE
go run cmd/makeconfig/config.go 初始化配置文件错误

### ISSUE THREAD

**Issue by hlz217057** [hyahm/ITflow#8]
E:\ITflow\go\cmd\makeconfig\config.go:7:2: cannot find package "github.com/hyahm/goconfig" in any of:
        E:\go\src\github.com\hyahm\goconfig (from $GOROOT)
        C:\Users\Administrator\go\src\github.com\hyahm\goconfig (from $GOPATH)

**Comment by hyahm** [comment]
执行 这个试试
```
go clean --modcache
```

**Comment by hlz217057** [comment]
> 1. go的版本必须> = 1.12
> 2. 执行这个试试
> 
> ```
> go clean --modcache
> ```

还是不行，没效果

**Comment by hyahm** [comment]
你go的版本是多少

**Comment by hlz217057** [comment]
> 你go的版本和系统版本是多少
> 我看你的go版本是低于1.12的一样子
> 
> ```shell
> go version
> ```

go version go1.15.2 windows/amd64

**Comment by hyahm** [comment]
![image](https://user-images.githubusercontent.com/22030094/95572472-95b70280-0a5c-11eb-8180-e37a6cba4e70.png)

这是我刚试的， 无法运行是因为数据库没连

**Comment by hlz217057** [comment]
> ![image](https://user-images.githubusercontent.com/22030094/95572472-95b70280-0a5c-11eb-8180-e37a6cba4e70.png)
> 
> 这是我刚试的， 无法运行是因为数据库没连
> 
> 在ITflow\go目录下面 执行看看
> 
> ```
> go get github.com/hyahm/goconfig
> ```

![image](https://user-images.githubusercontent.com/32893570/95573429-04489000-0a5e-11eb-9c9f-19dc14d5fb48.png)

**Comment by hyahm** [comment]
那就没问题了

**Comment by hlz217057** [comment]
> 那就没问题了
连接数据库除了 sql.go修改，还有哪些地方需要配置？

**Comment by hyahm** [comment]
![image](https://user-images.githubusercontent.com/22030094/95573914-c13aec80-0a5e-11eb-97a4-39e3bd0ea08c.png)

改配置文件bug.ini,  其他的没什么改的

**Comment by hlz217057** [comment]
> ![image](https://user-images.githubusercontent.com/22030094/95573914-c13aec80-0a5e-11eb-97a4-39e3bd0ea08c.png)
> 
> # 存放图片的目录
> imgdir = /data/bugimg/
> 
> # 图片显示的地址(用接口的地址)
> showbaseurl = http://127.0.0.1:10001/showimg/
> 
> 改配置文件bug.ini, 其他的没什么改的

![image](https://user-images.githubusercontent.com/32893570/95574518-a5841600-0a5f-11eb-98dc-a4a64701d1b9.png)
http://127.0.0.1:10001/showimg/  访问不成功。

**Comment by hyahm** [comment]
这个是拼接图片的地址。本来就直接访问不了
