### ISSUE TITLE
登录 NetWork Error

### ISSUE THREAD

**Issue by hlz217057** [hyahm/ITflow#9]
一个电脑环境搭建完成，在本地环境操作都是可以的，同一局域网下，用其他电脑登录提示 NetWork Error，怎么解决？？？？

**Comment by hyahm** [comment]
确保前端配置文件的接口是局域网的地址

**Comment by hlz217057** [comment]
> 确保前端配置文件的接口是局域网的地址

login页有啊，点击登录不行，还是说需要tomcat配置？？

**Comment by hyahm** [comment]
看你前端代码是怎么运行的。如果是直接
`npm run dev`
修改前端根目录的. env. development文件的VUE_APP_BASE_API
否则修改. env.production
